version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bumpp
  - defu
  - eslintcache
  - importantimport
  - masknet
  - mportant
  - pkgroll
  - sonarjs
ignoreWords: []
import: []
