name: Changesets

on:
  push:
    paths:
      - .changeset/**
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2
        id: pnpm-install
        with:
          version: latest
          run_install: false
      
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: latest
          registry-url: 'https://registry.npmjs.org'

      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - run: pnpm install --frozen-lockfile

      - uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: 'chore: 🔖 update versions'
          title: 'chore: 🔖 update versions'
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
